### ISSUE TITLE
Dirigible code style guidelines

### ISSUE THREAD

**Issue by SvetlinZarev** [SAP/cloud-dirigible#125]
It would be good to have *official* dirigible code style guidelines in order to maintain consistent and good looking code base. Reasonable requirements should be set for at least:
 
* maximum line length
* maximum length of comment lines
* source encoding 
* line endings (UNIX, Mac, Windows ?)
* tabs or spaces (if spaces - whats the required number of spaces)
* indentation 
* braces (should "if"s with single line statement be enclosed in {}, should "case" blocks be enclosed in {}, etc)
* naming conventions (A lot of interfaces for instance (maybe all)  start with I, and this should be documented somewhere)
* other topics not mentioned here

It would be great if there are ready to use eclipse (IntelliJ, Netbeans, etc) code formatter settings, which contributors can download and import into their IDE.

**Comment by ThuF** [comment]
Transfered to https://bugs.eclipse.org/bugs/show_bug.cgi?id=476165
