### ISSUE TITLE
Error: Could not create the view

### ISSUE THREAD

**Issue by Ponsen** [SAP/cloud-dirigible#171]
Hello,

I followed the steps for building and deploying Dirigible on my local Tomcat7 Server, but on almost every view I receive error messages. Index-Site looks good.

Any ideas?

IDE:
Could not create the view: com.sap.dirigible.repository.api.RepositoryCreationException: Repository provider has NOT been registered

Repository:
Oh snap! 500 - <html><head><title>Apache Tomcat/7.0.52 (Ubuntu) - Error report</title><style></style> </head><body><h1>HTTP Status 500 - Could not initialize repository.</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>Could not initialize repository.</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>javax.servlet.ServletException: Could not initialize repository. com.sap.dirigible.runtime.registry.AbstractRegistryServlet.initRepository(AbstractRegistryServlet.java:72) com.sap.dirigible.runtime.registry.AbstractRegistryServlet.service(AbstractRegistryServlet.java:59) javax.servlet.http.HttpServlet.service(HttpServlet.java:727) org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38) com.sap.dirigible.runtime.filter.AccessLogFilter.doFilter(AccessLogFilter.java:62) org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) com.sap.dirigible.runtime.filter.CorsFilter.doFilter(CorsFilter.java:44) org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) com.sap.dirigible.runtime.filter.XSSFilter.doFilter(XSSFilter.java:40) org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) com.sap.dirigible.runtime.filter.SandboxFilter.doFilter(SandboxFilter.java:65) org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132) org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60) javax.servlet.http.HttpServlet.service(HttpServlet.java:727) org.eclipse.equinox.servletbridge.BridgeServlet.service(BridgeServlet.java:138) com.sap.dirigible.ide.bridge.DirigibleBridge.service(DirigibleBridge.java:69) javax.servlet.http.HttpServlet.service(HttpServlet.java:727) com.sap.dirigible.ide.bridge.ext.XSSFilter.doFilter(XSSFilter.java:40) com.sap.dirigible.ide.bridge.ext.ExpiresFilter.doFilter(ExpiresFilter.java:47) </pre></p><p><b>root cause</b> <pre>com.sap.dirigible.repository.api.RepositoryException: com.sap.dirigible.repository.api.RepositoryCreationException: Repository provider has NOT been registered com.sap.dirigible.runtime.repository.RepositoryFacade.getRepository(RepositoryFacade.java:89) com.sap.dirigible.runtime.registry.AbstractRegistryServlet.initRepository(AbstractRegistryServlet.java:66) com.sap.dirigible.runtime.registry.AbstractRegistryServlet.service(AbstractRegistryServlet.java:59) javax.servlet.http.HttpServlet.service(HttpServlet.java:727) org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38) com.sap.dirigible.runtime.filter.AccessLogFilter.doFilter(AccessLogFilter.java:62) org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) com.sap.dirigible.runtime.filter.CorsFilter.doFilter(CorsFilter.java:44) org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) com.sap.dirigible.runtime.filter.XSSFilter.doFilter(XSSFilter.java:40) org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) com.sap.dirigible.runtime.filter.SandboxFilter.doFilter(SandboxFilter.java:65) org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132) org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60) javax.servlet.http.HttpServlet.service(HttpServlet.java:727) org.eclipse.equinox.servletbridge.BridgeServlet.service(BridgeServlet.java:138) com.sap.dirigible.ide.bridge.DirigibleBridge.service(DirigibleBridge.java:69) javax.servlet.http.HttpServlet.service(HttpServlet.java:727) com.sap.dirigible.ide.bridge.ext.XSSFilter.doFilter(XSSFilter.java:40) com.sap.dirigible.ide.bridge.ext.ExpiresFilter.doFilter(ExpiresFilter.java:47) </pre></p><p><b>root cause</b> <pre>com.sap.dirigible.repository.api.RepositoryCreationException: Repository provider has NOT been registered com.sap.dirigible.repository.api.RepositoryFactory.createRepository(RepositoryFactory.java:34) com.sap.dirigible.runtime.repository.RepositoryFacade.getRepository(RepositoryFacade.java:85) com.sap.dirigible.runtime.registry.AbstractRegistryServlet.initRepository(AbstractRegistryServlet.java:66) com.sap.dirigible.runtime.registry.AbstractRegistryServlet.service(AbstractRegistryServlet.java:59) javax.servlet.http.HttpServlet.service(HttpServlet.java:727) org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180) org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38) com.sap.dirigible.runtime.filter.AccessLogFilter.doFilter(AccessLogFilter.java:62) org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) com.sap.dirigible.runtime.filter.CorsFilter.doFilter(CorsFilter.java:44) org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) com.sap.dirigible.runtime.filter.XSSFilter.doFilter(XSSFilter.java:40) org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) com.sap.dirigible.runtime.filter.SandboxFilter.doFilter(SandboxFilter.java:65) org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173) org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81) org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35) org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132) org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60) javax.servlet.http.HttpServlet.service(HttpServlet.java:727) org.eclipse.equinox.servletbridge.BridgeServlet.service(BridgeServlet.java:138) com.sap.dirigible.ide.bridge.DirigibleBridge.service(DirigibleBridge.java:69) javax.servlet.http.HttpServlet.service(HttpServlet.java:727) com.sap.dirigible.ide.bridge.ext.XSSFilter.doFilter(XSSFilter.java:40) com.sap.dirigible.ide.bridge.ext.ExpiresFilter.doFilter(ExpiresFilter.java:47) </pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.52 (Ubuntu) logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.52 (Ubuntu)</h3></body></html>

**Comment by ThuF** [comment]
Did you try to deploy with some of the released versions?
* https://github.com/SAP/cloud-dirigible/releases/tag/2.0.150121 (pre-release)
* https://github.com/SAP/cloud-dirigible/releases/tag/v1.3.39-beta (latest-release)
* https://github.com/SAP/cloud-dirigible/releases (all releases)

**Comment by ThuF** [comment]
To try again, please follow these steps:
* pull the sources
* build with the fix (**mvn clean install**)
* navigate to the **{tomcat-installation-folder}/bin/** and delete the **derby** folder
* navigate to the **{dirigible-repo-folder}/com.sap.dirigible/com.sap.dirigible.parent/releng/all.tomcat/target/dirigible-all-tomcat.war**
* rename the war file to **dirigible.war**
* deploy

Now it should work fine :)

**Comment by Ponsen** [comment]
Hi,

first things first: Thanks for your reply.

I pulled the newest source, build and deployed it again and finallly found out, why nothing was working:
I had no rights to write to the tomcat7 dir. I changed the permissions and now everything is working just fine.

Thanks again!
