### ISSUE TITLE
Import Content is not working

### ISSUE THREAD

**Issue by ThuF** [SAP/cloud-dirigible#185]
When importing content, it is imported under **/db/dirigible/registry/[project-name]**
The artifacts of the project should be imported under: 
* **/db/dirigible/registry/public/DataStructure/[package-name]/[artifact-name]**
* **/db/dirigible/registry/public/ExtensionDefinitions/[package-name]/[artifact-name]**
* **/db/dirigible/registry/public/IntegrationServices/[package-name]/[artifact-name]**
* ...

**Comment by delchev** [comment]
not sure about project-name - is it the additional package-name you mean?

**Comment by ThuF** [comment]
Actually, yes this is the package-name, I'll change the description of the issue.
