### ISSUE TITLE
Service URL of the generated Entity UI is wrong

### ISSUE THREAD

**Issue by delchev** [SAP/cloud-dirigible#187]
var url = '/dirigible/services/js/products/products/products.js';

should be

	var url = '/dirigible/services/js/products/products.js';

w/o {project} in the URL

related to #177

**Comment by dgiormov** [comment]
checkout this proposal: https://github.com/SAP/cloud-dirigible/commit/02fea8ebfe66e8ba84371a7d5c4bd625b888649d
