### ISSUE TITLE
Adapt Sample Projects for import

### ISSUE THREAD

**Issue by delchev** [SAP/cloud-dirigible#189]
https://dirigible.us1.hana.ondemand.com/dirigible/components/bootstrap/dist/js/bootstrap.min.js
+ service URLs

**Comment by delchev** [comment]
add package - sub-folder

**Comment by ThuF** [comment]
You mean these projects? https://github.com/SAP/cloud-dirigible-samples

**Comment by delchev** [comment]
yes, and their source at:
https://github.com/dirigible-io/

**Comment by ThuF** [comment]
Ok, I'll handle them.

**Comment by ThuF** [comment]
Fixed in:
* https://github.com/dirigible-io/
* https://github.com/SAP/cloud-dirigible-samples/commit/7a4b1a189e001e6a88bda9d7a64c8123c9cee4ff
