### ISSUE TITLE
[Tomcat] RepositoryCreationException: Repository provider has NOT been registered

### ISSUE THREAD

**Issue by ThuF** [SAP/cloud-dirigible#193]
com.sap.dirigible.repository.api.RepositoryCreationException: Repository provider has NOT been registered
	at com.sap.dirigible.repository.api.RepositoryFactory.createRepository(RepositoryFactory.java:41)
	at com.sap.dirigible.ide.repository.RepositoryFacade.getRepository(RepositoryFacade.java:63)
...

**Status:**

* Bundle **com.sap.dirigible.repository.db_2.0.150223**, status **INSTALLED**
* **Reason** - Missing required bundle **com.sap.dirigible.repository.db.init_0.0.0**

**Comment by dgiormov** [comment]
This might be the case that the plugin is missing in feature.xml, unfortunatelly I cannot confirm this due to 
https://github.com/SAP/cloud-dirigible/issues/194

here is the proposed change: https://github.com/SAP/cloud-dirigible/commit/ba9a6edff2235781822980ae961c9449548d2966

**Comment by delchev** [comment]
which Tomcat do you use? with 7.0 it is OK:
66      ACTIVE      com.sap.dirigible.repository.logging_2.0.150223
81      ACTIVE      com.sap.dirigible.ide.repository_2.0.150223
82      ACTIVE      com.sap.dirigible.repository.api_2.0.150223
83      ACTIVE      com.sap.dirigible.repository.zip_2.0.150223
84      ACTIVE      com.sap.dirigible.repository.db.init_2.0.150223
85      ACTIVE      com.sap.dirigible.repository.db_2.0.150223
86      ACTIVE      com.sap.dirigible.repository.ext_2.0.150223
87      ACTIVE      com.sap.dirigible.ide.repository.ui_2.0.150223

**Comment by ThuF** [comment]
Tomcat Version - 7.0.47

The proposed change: ba9a6ed does not fix the issue

**Comment by ThuF** [comment]
The problem is not persisted with **Tomcat - 7.0.59**
