### ISSUE TITLE
cannot build dirigible with maven on mac

### ISSUE THREAD

**Issue by dgiormov** [SAP/cloud-dirigible#194]
[INFO] Adding repository http://dirigible.io/p2/external
[ERROR] Internal error: java.lang.RuntimeException: Failed to resolve target definition /Users/user/git/cloud-dirigible/com.sap.dirigible/com.sap.dirigible.parent/platform/com.sap.dirigible.platform.target/com.sap.dirigible.platform.base.target: Problems resolving provisioning plan.: [Unable to satisfy dependency from org.eclipse.equinox.p2.core.feature.feature.group 1.2.1.v20140221-1852 to org.eclipse.equinox.security.macosx [1.100.200.v20130327-1442].] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to resolve target definition /Users/user/git/cloud-dirigible/com.sap.dirigible/com.sap.dirigible.parent/platform/com.sap.dirigible.platform.target/com.sap.dirigible.platform.base.target

**Comment by delchev** [comment]
which version of maven do you use - 3.0.x?

**Comment by dgiormov** [comment]
Apache Maven 3.1.1

**Comment by delchev** [comment]
try with 3.0.x

2015-02-26 11:01 GMT+02:00 dgiormov <notifications@github.com>:

**Comment by delchev** [comment]
<environments>
			            <environment>
			                <os>win32</os>
			                <ws>win32</ws>
			                <arch>x86</arch>
			            </environment>
			            <environment>
			                <os>linux</os>
			                <ws>gtk</ws>
			                <arch>x86</arch>
			            </environment>
			            <environment>
			                <os>macosx</os>
			                <ws>cocoa</ws>
			                <arch>x86</arch>
			            </environment>
			        </environments>
