### ISSUE TITLE
[Registry] Override previous content checkbox is not working

### ISSUE THREAD

**Issue by ThuF** [SAP/cloud-dirigible#199]
Importing registry content with **checked** checkbox *"Override previous content?"* result in the following request:
* https://[host]:[port]/dirigible/services/import?override=**undefined**

The result of the action should be this call:
* https://[host]:[port]/dirigible/services/import?override=**true**

**Comment by delchev** [comment]
transferred to:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=468656
